services:
  imadds:
    build: .
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
      - mongodb
      - kafka
    networks:
      - imadds-network
  
  spark-master:
    image: apache/spark:4.0.0-java21-python3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    networks:
      imadds-network:
        aliases:
          - spark-master
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker-1:
    image: apache/spark:4.0.0-java21-python3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 4g
    networks:
      - imadds-network

  spark-worker-2:
    image: apache/spark:4.0.0-java21-python3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 4g
    networks:
      - imadds-network

  mongodb:
    image: mongo:8.2.1
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=events
    restart: unless-stopped
    networks:
      imadds-network:
        aliases:
          - imaddsdb
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.15
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - imadds-network
  
  kafka:
    image: confluentinc/cp-kafka:7.2.15
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,EXTERNAL_DIFFERENT_HOST://:29093,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092,EXTERNAL_DIFFERENT_HOST://172.23.0.3:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT,EXTERNAL_DIFFERENT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - imadds-network
    ports:
      - "29092:29092"
      - "29093:29093"

networks:
  imadds-network:

volumes:
  mongodb_data:
