apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: imadds
spec:
  selector:
    matchLabels: { app: zookeeper }
  template:
    metadata:
      labels: { app: zookeeper }
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.2.15
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: imadds
spec:
  ports:
    - port: 2181
      name: zk
  selector:
    app: zookeeper